<section class="reviews" id="reviews">

  <div class="reviews__container">
    <h2 class="title">What our clients <br><span>say about us</span></h2>

    <div class="reviews__list">

        <span class="yelp-review" data-review-id="6N4t1zLjFuPR17XbMR7reA" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=lz9R6Eq1TcWpBPU-Tcn1KQ" rel="nofollow noopener">Benjamin N.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=6N4t1zLjFuPR17XbMR7reA" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>
        <span class="yelp-review" data-review-id="TKRGKF0I7SEgmQfRpmOkpQ" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=VyEvfrehO8bRjnclIzt0Og" rel="nofollow noopener">Jenny M.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=TKRGKF0I7SEgmQfRpmOkpQ" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>
        <span class="yelp-review" data-review-id="JvBLAQUiOWEdZFzvnJVQQg" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=EQiv9IKEtQwYyZVxf3uIow" rel="nofollow noopener">Thomas P.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=JvBLAQUiOWEdZFzvnJVQQg" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>
        <span class="yelp-review" data-review-id="X-kbr4zEFqPd9rit4MaSKA" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=GwokHdFwGTXLYVwTyCcDOg" rel="nofollow noopener">Jeremy P.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=X-kbr4zEFqPd9rit4MaSKA" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>
        <span class="yelp-review" data-review-id="AxwXelneoTU4OoYyFFh9_g" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=5FuhsUyCciePs75mCdEe_A" rel="nofollow noopener">J J.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=AxwXelneoTU4OoYyFFh9_g" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>
        <span class="yelp-review" data-review-id="IceehopkeFefErk4qsjygQ" data-hostname="www.yelp.com">Read <a href="https://www.yelp.com/user_details?userid=FRUI7l76RMFASiJ-M8FxYw" rel="nofollow noopener">Sochieta M.</a>'s <a href="https://www.yelp.com/biz/prime-air-group-brooklyn-4?hrid=IceehopkeFefErk4qsjygQ" rel="nofollow noopener">review</a> of <a href="https://www.yelp.com/biz/E4xPmRo7KPQQ-zWdYGHUEg" rel="nofollow noopener">Prime Air Group</a> on <a href="https://www.yelp.com" rel="nofollow noopener">Yelp</a><script src="https://www.yelp.com/embed/widgets.js" type="text/javascript" async></script></span>

    </div>

    <a class="button reviews__button" href="https://www.yelp.com/biz/prime-air-group-brooklyn-4">Leave your feedback</a>
  </div>

</section>
